-- 코드를 작성해주세요
SELECT COUNT(fi.FISH_TYPE) AS FISH_COUNT, fni.FISH_NAME
FROM FISH_INFO fi
INNER JOIN FISH_NAME_INFO fni
ON fni.FISH_TYPE = fi.FISH_TYPE
GROUP BY fi.FISH_TYPE, fni.FISH_NAME
ORDER BY FISH_COUNT DESC